version: '3.8'

services:
  mlflow-server:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow-server
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    environment:
      - MLFLOW_DISABLE_HOST_HEADER_VALIDATION=true
    networks:
      - traductor-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 10s
      timeout: 5s
      retries: 5

  traductor-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: traductor-app
    ports:
      - "7860:7860"
    env_file: .env
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-server:5000
      - PYTHONUNBUFFERED=1
    depends_on:
      mlflow-server:
        condition: service_healthy
    volumes:
      - ./mlruns:/mlflow/mlruns
    networks:
      - traductor-network

networks:
  traductor-network:
    driver: bridge

volumes:
  mlruns:
